# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-swift-cocoamqtt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal', '~> 1.0.1.20'

  # Pods for ios-swift-cocoamqtt

end
